version: '3'

services:
  mongodb:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    container_name: weibo-mongo

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    container_name: weibo-redis

  account:
    image: bossen/weibospider:v20.06.02
    volumes:
      - ./weiboPhoneDocker:/app
    depends_on:
      - mongodb
      - redis
    stdin_open: true
    tty: true
    container_name: weibo-account

  weibo-user:
    image: bossen/weibospider:v20.06.02
    volumes:
      - ./weiboPhoneDocker:/app
    depends_on:
      - mongodb
      - redis
    command: python run_spider.py user
    container_name: weibo-user

  weibo-tweet:
    image: bossen/weibospider:v20.06.02
    volumes:
      - ./weiboPhoneDocker:/app
    depends_on:
      - mongodb
      - redis
    command: python run_spider.py tweet
    container_name: weibo-tweet